# Generated by Django 4.2.5 on 2023-09-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0003_ingredient_alter_cook_years_of_experience_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
