# Generated by Django 4.2.5 on 2023-10-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0005_rename_ingredient_dish_ingredients"),
    ]

    operations = [
        migrations.AddField(
            model_name="cook",
            name="user_image",
            field=models.ImageField(null=True, upload_to="cooks"),
        ),
        migrations.AddField(
            model_name="dish",
            name="image",
            field=models.ImageField(null=True, upload_to="dishes"),
        ),
    ]
