# Generated by Django 4.2.5 on 2023-10-03 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0007_dish_created_by_dishtype_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="user_image",
            field=models.ImageField(
                null=True,
                upload_to="cooks",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="image",
            field=models.ImageField(
                null=True,
                upload_to="dishes",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif"]
                    )
                ],
            ),
        ),
    ]
